### ISSUE TITLE
 attribute lookup CalibData on pykitti.odometry failed

### ISSUE THREAD

**Issue by Tang-cx5** [Brummi/MonoRec#29]
Hi,when I set up the dataset,runing the order
       python train.py --config configs/train/monorec/monorec_depth.json --options stereo  
"enumerate(self.data_loader)"    will alert pickle.PicklingError: Can't pickle <class 'pykitti.odometry.CalibData'>: attribute lookup CalibData on pykitti.odometry failed

**Comment by BinBCheng** [comment]
Had the same problem, +1

**Comment by Tang-cx5** [comment]
If you run it with Windows, set "numworks" = 0.Because numworks means multiprogress data,Windows forbids it






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月10日(星期天) 晚上9:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Brummi/MonoRec]  attribute lookup CalibData on pykitti.odometry failed (Issue #29)





 
Had the same problem, +1

**Comment by BinBCheng** [comment]
Hi, thank you for your reply, it is greatly useful for me and i solve this issue. But now,when i try to run train.py&nbsp; i meet the bug "TypeError: 'tuple' object is not callable", and this is my kitti dataset, could you help me solve this issue, thank you sincerely.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Brummi/MonoRec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月11日(星期一) 上午7:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Brummi/MonoRec]  attribute lookup CalibData on pykitti.odometry failed (Issue #29)





 If you run it with Windows, set "numworks" = 0.Because numworks means multiprogress data,Windows forbids it 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年4月10日(星期天) 晚上9:01 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 主题: Re: [Brummi/MonoRec]  attribute lookup CalibData on pykitti.odometry failed (Issue #29) 
 
 
 
 
 
   
 Had the same problem, +1
