### ISSUE TITLE
Nuscenes dataset inverse depth map generation from lidar file

### ISSUE THREAD

**Issue by fish258** [Brummi/MonoRec#33]
Hi Felix,

I'm trying to run the monorec on the Nuscenes dataset. The visualization results seem decent. But the quantitative metrics are abnormal (e.g. Abs_rel_sparse_metric reaches 0.5) when I evaluate it. 

I guess maybe the GT depth map caused this. I generate inverse depth maps for nuscenes dataloader by using 1/depth (pixel wise). Does this remain the same distribution as the training process?

Could you help me with this?

**Comment by Brummi** [comment]
Hi!

I think you are right. Investigating the lidar ground truth would be the best way to find the problem. Otherwise, it could also be the scale of the predictions (by default, Monorec predicts between 3m and 400m (inv 0.33 - 0.0025).
I would suggest a couple of things:

- Try out not inverting the depth. Maybe there is another step in your data pipeline that already does that.
- Debug the evaluation and plot the predicted depth vs gt. depth. (you will see whether you have to invert. if it looks similar, but the scale is off, try to fix the monorec depth range or try to adjust your lidar range).
