### ISSUE TITLE
Why set temporal frames from default 2 to 10 when 'lidar_depth' and 'annotated_lidar' are enabled?

### ISSUE THREAD

**Issue by ruili3** [Brummi/MonoRec#40]
Hi,

Thank you al lot for your impressive work.

I found a place that I do not understand. As shown in the code below 
https://github.com/Brummi/MonoRec/blob/b2b3decc130d9ca333d1350096b9838a12f977a3/data_loader/kitti_odometry_dataset.py#L56-L58

why set the nearby frames from default 2 to at least 10 when 'lidar_depth' and 'annotated_lidar' are enabled. Is it a general setting for both training and testing or only a setting for testing? Thank you!

**Comment by Brummi** [comment]
Thank you for showing interest in our work!

If I remember correctly, this is because the annotated lidar is not available for the 5 first and 5 last frames of a sequence. (they are generated by aggregating lidars over multiple timesteps).
Therefore, we have to make sure to ignore the first and last 5 frames in the sequence (-> extra frames >= 10, offset >= 5).

Best,
Felix

**Comment by ruili3** [comment]
Oh I understand, so the number of adjacent frames is not changed (==2), and
only the first and last 5 frames are overlooked. Do I understand it
correctly?

Best

**Comment by Brummi** [comment]
You are right :)
