### ISSUE TITLE
How to use kitti raw dataset instead of kitti odometry dataset?

### ISSUE THREAD

**Issue by AslauAlexandru** [Brummi/MonoRec#47]

**Comment by Brummi** [comment]
Hi,
thanks for your interest in our work and sorry for the late reply!

You would have to do a few changes to the KITTI Odometry dataset.
Otherwise, you can also wait for the release of our most recent project [github.com/Brummi/BehindTheScenes](https://github.com/Brummi/BehindTheScenes) .
We will release the code in a few days and it contains a KITTI Raw dataset implementation and poses precomputed from ORB-SLAM3.

Hope this helps!
Best,
Felix

**Comment by Brummi** [comment]
Hi,
just wanted to let you know that the code for Behind The Scenes has been released and the dataset implementation for KITTI Raw should be fairly compatible with the data format in Monorec.
[github.com/Brummi/BehindTheScenes](https://github.com/Brummi/BehindTheScenes)
The repo also contains precomputed poses from ORB-SLAM3.

Best,
Felix
